- name: install debian prerequisites
  apt:  name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - git
    - build-essential
    - gcc
    - apache2
    - libapache2-mod-wsgi